#!/usr/bin/env bash
if ! command -v qsub_local >/dev/null 2>&1 && [[ $- != *i* ]]; then
  exec bash -i "$0" "$@"
fi
set -euo pipefail
cd /home/exouser/StormSurge

qsub_local train.sh WQEF_CBBT_G0E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G0_E0_T0.sh
qsub_local train.sh WQEF_Boston_G0E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G0_E0_T0.sh
qsub_local train.sh WQEF_Battery_G0E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G0_E0_T0.sh
qsub_local train.sh WQEF_Lewes_G0E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G0_E0_T0.sh
qsub_local train.sh WQEF_CBBT_G0E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G0_E0_T1.sh
qsub_local train.sh WQEF_Boston_G0E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G0_E0_T1.sh
qsub_local train.sh WQEF_Battery_G0E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G0_E0_T1.sh
qsub_local train.sh WQEF_Lewes_G0E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G0_E0_T1.sh
qsub_local train.sh WQEF_CBBT_G0E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G0_E1_T0.sh
qsub_local train.sh WQEF_Boston_G0E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G0_E1_T0.sh
qsub_local train.sh WQEF_Battery_G0E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G0_E1_T0.sh
qsub_local train.sh WQEF_Lewes_G0E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G0_E1_T0.sh
qsub_local train.sh WQEF_CBBT_G0E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G0_E1_T1.sh
qsub_local train.sh WQEF_Boston_G0E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G0_E1_T1.sh
qsub_local train.sh WQEF_Battery_G0E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G0_E1_T1.sh
qsub_local train.sh WQEF_Lewes_G0E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G0_E1_T1.sh
qsub_local train.sh WQEF_CBBT_G1E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G1_E0_T0.sh
qsub_local train.sh WQEF_Boston_G1E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G1_E0_T0.sh
qsub_local train.sh WQEF_Battery_G1E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G1_E0_T0.sh
qsub_local train.sh WQEF_Lewes_G1E0T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G1_E0_T0.sh
qsub_local train.sh WQEF_CBBT_G1E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G1_E0_T1.sh
qsub_local train.sh WQEF_Boston_G1E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G1_E0_T1.sh
qsub_local train.sh WQEF_Battery_G1E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G1_E0_T1.sh
qsub_local train.sh WQEF_Lewes_G1E0T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G1_E0_T1.sh
qsub_local train.sh WQEF_CBBT_G1E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G1_E1_T0.sh
qsub_local train.sh WQEF_Boston_G1E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G1_E1_T0.sh
qsub_local train.sh WQEF_Battery_G1E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G1_E1_T0.sh
qsub_local train.sh WQEF_Lewes_G1E1T0 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G1_E1_T0.sh
qsub_local train.sh WQEF_CBBT_G1E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_CBBT_G1_E1_T1.sh
qsub_local train.sh WQEF_Boston_G1E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Boston_G1_E1_T1.sh
qsub_local train.sh WQEF_Battery_G1E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Battery_G1_E1_T1.sh
qsub_local train.sh WQEF_Lewes_G1E1T1 configs/0922_wqe_factorial_multickpt/train_config_NCEP_Lewes_G1_E1_T1.sh
