#!/usr/bin/env bash

TRAIN_PY="train.py"
num_gpus=4
TEST_ROOT_DIR=""
ENCODER_TYPE="GraphSAGE"
CNN_INTERMEDIATE_CHANNEL=29
TEMPORAL_BLOCK="Transformer"
HEAD_TYPE="dual"

BATCH_SIZE=256
LR_LIST=("5e-3")

EPOCHS=300
HIDDEN_CHANNELS=128
NUM_LAYERS=2
DROPOUT=0.05
HEAD_DROPOUT=0.05
SEED=42
SHUFFLE_YEARS=0
FUTURE_ONLY=0
FUTURE_YEAR_THRESHOLD=2030

LOSS_MODE_LIST=("mse")
TAIL_FRAC="0.05"
TAIL_LAMBDA_LIST=("0.1")

WMSE_Q_LIST=("95")
WMSE_ALPHA="4.0"
WMSE_S="0.10"
WMSE_USE_ABS="1"

SLOPE_LAMBDA_LIST=("0.10")
SLOPE_MASK_S_LIST=("0.10")
SLOPE_ROBUST="charb"
SLOPE_CHARB_EPS="1e-3"
SLOPE_HUBER_DELTA="0.05"

SCHEDULER="cosine"
ROP_METRIC="val_rmse_phys"

# Dual prediction head only; ignored when HEAD_TYPE="single".
GATE_MODE="window"
DUAL_MODE="exceedance"
DUAL_LOSS=1
EXCEEDANCE_PERCENTILE=95
DUAL_ABLATION="none"
BODY_LOSS_WEIGHT=1
EXCESS_LOSS_WEIGHT=1
GATE_LOSS_WEIGHT=1

NODE_READ_HEADS="8"
TIME_READ_HEADS="8"
TRANSFORMER_LAYERS="2"
TRANSFORMER_FF_MULT="4.0"
TRANSFORMER_DROPOUT="0.0"
MAX_TIME_STEPS="32"

STATION_JSON_DIR="./station_json"
USE_SITE_ELEVATION=1
USE_BATHYMETRY=0

X_NORM="zscore"
X_P_LO="1.0"
X_P_HI="99.0"
X_NODES_PER_GRAPH="0"
X_CLIP="6.0"

X_AUG="1"
X_AUG_PROB="0.5"
X_AUG_SCALE="0.02"
X_AUG_BIAS="0.02"

DISABLE_OOD="1"

USE_AMP=1
AMP_DTYPE="bf16"
USE_TF32=1
TORCH_THREADS=1

NUM_WORKERS=0
PIN_MEMORY=0
PERSISTENT_WORKERS=0
PREFETCH_FACTOR=0
MP_CONTEXT="fork"

USE_TMUX="${USE_TMUX:-1}"

DO_CONDA=1
CONDA_MODULE="anaconda"
CONDA_SH="/software/u22/anaconda/python3.9/etc/profile.d/conda.sh"
CONDA_ENV="torchpyg-cu124"
