#!/usr/bin/env bash
# Fresh WQE/Tail factorial (four VAL-only checkpoint roles): CBBT / G0_E0_T1.

TRAIN_PY="train.py"
DO_CONDA=0
# Explicit runtime survives queue workers and tmux shell initialization.
PYTHON_BIN="${WQEF_PYTHON_BIN:-/home/exouser/.conda/envs/torchpyg-cu12x/bin/python}"
num_gpus=1
USE_TMUX="${USE_TMUX:-1}"

ROOT_DIR="./Data/Grid4_New/NCEP/graphs"
TEST_ROOT_DIR=""
STATION="CBBT"
MODEL="perceiver3"
ENCODER_TYPE="GraphSAGE"
CNN_INTERMEDIATE_CHANNEL=29
TEMPORAL_BLOCK="Transformer"
HEAD_TYPE="dual"
HISTORY_HOURS_LIST=(24)
HIDDEN_CHANNELS=128
NUM_LAYERS=2
DROPOUT=0.05
HEAD_DROPOUT=0.05
NODE_READ_HEADS=8
TIME_READ_HEADS=8
TRANSFORMER_LAYERS=2
TRANSFORMER_FF_MULT=4.0
TRANSFORMER_DROPOUT=0.0
MAX_TIME_STEPS=32

TRAIN_RATIO="0.6"
VAL_RATIO="0.2"
SHUFFLE_YEARS=0
FUTURE_ONLY=0
FUTURE_YEAR_THRESHOLD=2030
SEED=42
STATION_JSON_DIR="./station_json"
USE_SITE_ELEVATION=0
USE_BATHYMETRY=0

X_NORM="zscore"
DISABLE_OOD=1
X_P_LO="1.0"
X_P_HI="99.0"
X_NODES_PER_GRAPH=0
X_CLIP=0
X_AUG=0
X_AUG_PROB=0
X_AUG_SCALE=0
X_AUG_BIAS=0

BATCH_SIZE=256
GRAD_ACCUM_STEPS=4
LR_LIST=("5e-3")
EPOCHS=300
SCHEDULER="cosine"
WARMUP_EPOCHS=5
WARMUP_START_FACTOR=0.1
MIN_LR=1e-6
MAX_GRAD_NORM=0
DETERMINISTIC=0
# Inactive ReduceLROnPlateau defaults.
ROP_METRIC="val_all_rmse"
ROP_FACTOR=0.5
ROP_PATIENCE=20
ROP_THRESHOLD=1e-4
ROP_COOLDOWN=0
ROP_MIN_LR=1e-6

USE_AMP=1
AMP_DTYPE="bf16"
USE_TF32=1
NUM_WORKERS=0
TORCH_THREADS=1
PIN_MEMORY=0
PERSISTENT_WORKERS=0
PREFETCH_FACTOR=0
MP_CONTEXT="fork"

LOSS_MODE_LIST=("mse")
EXCESS_LOSS_MODE="mse"
WQE_QUANTILE_TAU=0.25
WQE_EXPECTILE_TAU=0.82
WQE_QUANTILE_WEIGHT=0.16666666666666667
WQE_EXPECTILE_WEIGHT=0.83333333333333333
EXCEEDANCE_LOSS_WEIGHT=0.025
EXCESS_AMP_LOSS_WEIGHT=0

# These head/branch settings are inactive for Single.
DUAL_MODE="exceedance"
EXCESS_FORMULATION="direct"
EXCEEDANCE_HEAD_EXPERIMENT=""
EXCEEDANCE_GATE_POOLING="mean"
GATE_MODE="window"
DUAL_ABLATION="none"
DUAL_LOSS=1
EXCEEDANCE_PERCENTILE=95
BODY_LOSS_WEIGHT=1
EXCESS_LOSS_WEIGHT=2
GATE_LOSS_WEIGHT=0.5
SHAPE_LOSS_WEIGHT=0
SEVERITY_SHAPE_EPS=1e-6

CHECKPOINT_SELECTION="overall"

ALL_RESULTS_ROOT="/home/exouser/media/share/PACT/All_results_0922_wqe_factorial_multickpt"
RUN_DIR_NAME_STYLE="runname_timestamp"
PACT_RUN_NAME="NCEP_CBBT_G0_E0_T1"
PYTHON_RUN_TAG_BASE="NCEP_CBBT_G0_E0_T1"
